version: '2.0'
services:
  db:
    image: postgres
  elasticsearch:
    image: elasticsearch:alpine
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
  web:
    build: .
    volumes:
      - .:/weather_me
    ports:
      - "3000:3000"
    depends_on:
      - db
      - elasticsearch
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
volumes:
  elasticsearch: {}