json.id @group_event.id
json.name @group_event.name
json.description @group_event.description
json.state @group_event.state
json.start_date @group_event.start_date
json.end_date @group_event.end_date
json.location @group_event.location
json.latitude @group_event.latitude
json.longitude @group_event.longitude